### ISSUE TITLE
Request for including two small changes in the UI

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/Open_Crypto_Tracker#15]
I would like to request to include two small modifications in the UI
1. It would be good if almost all the tabs in the UI can be toggled from the main settings so that the one can control the presence of the tabs in the app.
![Screenshot_2020-08-28 DFD Cryptocoin Values - Portfolio Tracker(1)](https://user-images.githubusercontent.com/20767253/91593748-533ed800-e97e-11ea-931f-674a9d66f809.png)
2. It would be nice if the values or the entry present between the Setting and the theme are visible to the admin of the app.

**Comment by taoteh1221** [comment]
I myself like not having to login to see basic config file parameters that don't reveal anything significant regarding personal settings (email address, phone number, etc are never shown). I also like minimizing non-critical additions to config.php, since it's getting to be a few thousand lines of code already. That said, I'll leave this issue open and tag it for community feedback. If enough people agree they'd also like to see any of these changes, then I am happy to add them.

**Comment by taoteh1221** [comment]
No community feedback in almost 2 years on this, so I'm closing. I still don't like the ideas myself in this feature request, from a feasibility / UX viewpoint.
